[package]
name = "ssm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
ndarray = "0.17.1"
ndarray-npy = "0.10.0"
ndarray-rand = "0.16.0"
rand = "0.9.2"
rayon = "1.11.0"
regex = "1.12.2"
